apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-testing-tenant
  namespace: threescale-testing
spec:
  email: test@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale
  organizationName: testing
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: 3scale
  systemMasterUrl: 'https://master.apps.cluster-fs6z5.dynamic.redhatworkshops.io'
  tenantSecretRef:
    name: tenant-secret
  username: admin
