apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  name: developeruser5
spec:
  username: myusername5
  email: myusername5@example.com
  passwordCredentialsRef:
    name: myusername01
  role: admin
  developerAccountRef:
    name: developeraccount5
  providerAccountRef:
    name: tenant-secret