apiVersion: capabilities.3scale.net/v1beta1
kind: Application
metadata:
  name: example4
spec:
  accountCR:
    name: developeraccount4
  applicationPlanName: plan_basic
  productCR:
    name: echo-api-product-sample
  name: application_004
  description: describe_your_application