apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: petstore-sample
spec:
  applicationPlans:
    plan_basic:
      limits:
        - metricMethodRef:
            systemName: hits
          period: day
          value: 30
      name: Basic
    plan_unlimited:
      name: Unlimited
  providerAccountRef:
    name: tenant-secret
  name: Swagger Petstore
  systemName: Swagger_Petstore
  description: Swagger Petstore
