apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: echo-api-product-sample5
spec:
  applicationPlans:
    plan_basic:
      limits:
        - metricMethodRef:
            systemName: hits
          period: day
          value: 30
      name: Basic
    plan_unlimited:
      name: Unlimited
  providerAccountRef:
    name: tenant-secret
  name: Operator Product Echo API 5
  systemName: echo_api_product5
  description: Echo API Product 5
  backendUsages:
    echo_api_backend:
      path: /
